version: "3"
services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - misskey_external_network

  certbot:
    image: certbot/dns-cloudflare:latest
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./certbot.ini:/certbot.ini
    command: ["--version"]

networks:
  misskey_external_network:
    external: true
