version: "3"
services:
  nginx:
    image: nginx:1.25.3-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - misskey_external_network
      - misskey_internal_network
    environment:
      - TZ=Asia/Tokyo

  web:
    #build: .
    image: misskey/misskey:2023.11.1
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - misskey_external_network
      - misskey_internal_network
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro
    environment: 
      - TZ=Asia/Tokyo

  redis:
    restart: always
    image: redis:7.2-alpine
    networks:
      - misskey_internal_network
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      timeout: 30s
      retries: 20

  db:
    restart: always
    image: postgres:15.5-alpine
    networks:
      - misskey_internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      timeout: 30s
      retries: 20

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "TAKE_FILE_OWNERSHIP=111"
#    networks:
#      - misskey_internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data

  certbot:
    image: certbot/dns-cloudflare:v2.8.0
    networks:
      - misskey_external_network
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./certbot.ini:/certbot.ini
    command: ["--version"]

  mackerel:
    restart: always
    image: mackerel/mackerel-agent:0.78.1
    env_file: .config/mackerel.env
    environment:
      - enable_docker_plugin=1
      - auto_retirement=0
      - opts=-v
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/mackerel-agent/:/var/lib/mackerel-agent/
    networks:
      - misskey_internal_network
      - misskey_external_network
    dns:
      - 1.1.1.1

networks:
  misskey_internal_network:
    internal: true
  misskey_external_network:
    external: true
